# Project information
site_name: nVotes documentation
site_description: 'A short description of my project'
site_author: 'Felix Robles'
site_url: 'https://github.com/Findeton/agora-docs'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/Findeton/agora-docs'

# Copyright
copyright: 'GNU GPL 3.0 Copyright (c) 2016 Agora Voting'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Pages
pages:
- How to use nVotes: index.md
- User types: user-types.md
- Admin account creation: admin-account-creation.md
- Admin console: admin-console.md
- Election creation:
    - Basic details: election-creation/basic-details.md
    - Questions: election-creation/questions.md
    - Authentication: election-creation/authentication.md
    - Census configuration: election-creation/census-configuration.md
    - Census data: election-creation/census-data.md
    - Create election: election-creation/create-election.md
- Elections management: elections-management.md
- FAQ: faq.md
- Sending SMS: sending-sms.md
- Unsupported tally systems and vote list extraction: unsupported-tally-systems.md

# Options
extra:
#  version: '0.1.0'
  logo: 'images/logo.png'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'my-github-handle'
    twitter: 'my-twitter-handle'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '¶'